{
  schema:
  {
    name: configuration,
    type: map,
    required-entries:
    [
      {name: first-name, type: string},
      {name: last-name, type: string},
      {name: money, type: tag, tag: double-tagged},
      {name: human, type: bool},
      {name: age, type: unsigned-integer},
      {name: family, type: vector, elements: {name: family-member, type: string}},
      {name: velocities, type: vector, elements: {name: velocity, type: tag, tag: velocity}},
    ],
    optional-entries:
    [
      {
        name: money2, 
        type: selector, 
        options: 
        [
          {name: money2-float, type: float}, 
          {name: money2-bool, type: bool},
        ]
      },
    ],
  },
  tags:
  [
    {name: double-tagged, type: double},
    {
      name: velocity,
      type: selector,
      options:
      [
        {
          name: velocities,
          type: vector,
          elements: {name: velocity, type: double},
          minimum-length: 3,
          maximum-length: 3,
        },
        {
          name: speed and direction,
          type: map,
          required-entries:
          [
            {name: speed, type: double},
            {name: direction, type: vector, elements: {name: direction, type: double}},
          ],
        },
        {
          name: speed of sound and Mach number and direction,
          type: map,
          required-entries:
          [
            {name: speed-of-sound, type: double},
            {name: Mach, type: double},
            {name: direction, type: vector, elements: {name: direction, type: double}},
          ],
        },
      ],
    }
  ],
}
